#include QMK_KEYBOARD_H

enum layers {
    HALMAK,
}
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

  [HALMAK] = LAYOUT(
KC_GRV,	KC_1,	KC_2,	KC_3,	KC_4,	KC_5,	KC_6,	KC_7,	KC_8,	KC_9,	KC_0,	KC_BSPC,
KC_TAB,	KC_W,	KC_L,	KC_R,	KC_B,	KC_Z,	KC_SEMI,KC_Q,	KC_U,	KC_D,	KC_J,	KC_BSLS,
KC_ESC,	KC_S,	KC_H,	KC_N,	KC_T,	KC_COMM,KC_DOT,	KC_A,	KC_E,	KC_O,	KC_I,	KC_QUOT,
KC_LSFT,KC_F,	KC_M,	KC_V,	KC_C,	KC_SLSH,KC_G,	KC_P,	KC_X,	KC_K,	KC_Y,	MOD_LSFT,
KC_LCTL,KC_LALT,KC_LGUI,LOWER,	RAISE,	KC_SPC,	KC_SPC,	KC_LEFT, KC_DOWN, KC_UP,KC_RGHT,KC_RET
)
}
